[package]
name = "hikami_zbs"
version = "0.1.0"
edition = "2024"

[lints.clippy]
pedantic = "warn"
missing_docs_in_private_items = "warn"

[lints.rust]
missing_docs = "warn"

[lints.rustdoc]
missing_crate_level_docs = "warn"

[dependencies]
raki = { git = "https://github.com/Alignof/raki", branch = "feature/zbs" }
spin = "0.9.8"

hikami_core = { git = "https://github.com/Alignof/hikami", branch = "feature/milkv-megrez" }
